apiVersion: release-notes/v2
kind: feature
area: installation
issue:
  - 43204
releaseNotes:
- |
  **Enabled** templated CRD installation in the `base` chart by default.
  **Deprecated** `Values.base.enableCRDTemplates`. This option now defaults to `true` and will be removed
  in a future release. Until then, the legacy behavior can be enabled by setting this to `false`
upgradeNotes:
- title: Istio CRDs are templated by default and should be installed and upgraded via `helm install base`
  content: |
    This changes how CRDs are upgraded.
    Previously, we recommended:

    - Install: `helm install base`
    - Upgrade: `kubectl apply -f manifests/charts/base/crds`
    - Uninstall: `kubectl get crd -oname | grep --color=never 'istio.io' | xargs kubectl delete`

    This allows:

    - Install: `helm install base`
    - Upgrade: `helm upgrade base`
    - Uninstall: `kubectl get crd -oname | grep --color=never 'istio.io' | xargs kubectl delete`

    As a necessary consequence of this, the labels on the CRDs are changed to be consistent with other Helm-installed resources. If desired, the legacy non-Helm-upgradable CRDs and labels can be generated by setting `Values.base.enableCRDTemplates=false` during `helm install base`, but this option will be removed in a future release.
