apiVersion: release-notes/v2
kind: feature
area: installation
issue:
  - 43204
releaseNotes:
- |
  **Enabled** templated CRD installation in the `base` chart by default.
  This changes how CRDs are upgraded.
  Previously, we recommended:

  - Install: `helm install base`
  - Upgrade: `kubectl apply -f manifests/charts/base/crds` (this ~sorta worked)
  - Uninstall: `kubectl get crd -oname | grep --color=never 'istio.io' | xargs kubectl delete`

  This allows:

  - Install: `helm install base`
  - Upgrade: `helm upgrade base`
  - Uninstall: `kubectl get crd -oname | grep --color=never 'istio.io' | xargs kubectl delete`

  **Deprecated** `Values.base.enableCRDTemplates`. This option now defaults to `true` and will be removed
  in a future release. Until then, the legacy behavior can be enabled by setting this to `false`
