apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
  - 53949
releaseNotes:
- |
  **Fixed** DNS traffic (UDP and TCP) is now affected by traffic annotations like `traffic.sidecar.istio.io/excludeOutboundIPRanges` and `traffic.sidecar.istio.io/excludeOutboundPorts`. Before, UDP/DNS traffic would uniquely ignore these traffic annotations, because of the rule structure. The behavior change actually happened in the 1.23 release series, but was left out of the release notes for 1.23.
