apiVersion: release-notes/v2
kind: feature
area: installation
releaseNotes:
- |
  **Added** `dataplane` wrapper chart. This is a Helm wrapper chart that
  groups the existing individial Istio Helm charts, for easier install and upgrade, while still allowing
  Istio dataplane and controlplane upgrades to be managed separately as per Istio recommendation. Note that the `ambient` sample wrapper chart, which was never offically supported or recommended, is deprecated in favor of this, and will be removed in subsequent releases.

upgradeNotes:
  - title: Using the `dataplane` chart for new Istio installs
    content: |
      To install sidecar (without CNI agent):

      > $ helm install istio-controlplane istio-control/istio-discovery -n istio-system --create-namespace --set global.platform=(your-platform) --set global.profile=(your-profile)

      > $ helm install istio-dataplane istio/dataplane -n istio-system --create-namespace --set global.platform=(your-platform) --set global.profile=(your-profile) --set cni-agent.enabled=false

      To install sidecar (with CNI agent for sidecar repair/init container replacement):

      > $ helm install istio-controlplane istio-control/istio-discovery -n istio-system --create-namespace --set global.platform=(your-platform) --set global.profile=(your-profile)

      > $ helm install istio-dataplane istio/dataplane -n istio-system --create-namespace --set global.platform=(your-platform) --set global.profile=(your-profile) --set cni-agent.enabled=true

      To install ambient:

      > $ helm install istio-controlplane istio-control/istio-discovery -n istio-system --create-namespace --set global.platform=(your-platform) --set global.profile=ambient

      > $ helm install istio-dataplane istio/dataplane -n istio-system --create-namespace --set global.platform=(your-platform) --set global.profile=ambient

      To upgrade any of the above:

      > $ helm upgrade <istio-controlplane || istio-dataplane>

      Same, but with revisions:

      > $ helm upgrade istio-dataplane istio/dataplane -n istio-system --create-namespace --set global.platform=(whatever) --set global.profile=(whatever) --set base.defaultRevision=foo --set ztunnel.revision=foo

      > $ helm install istio-controlplane istio-control/istio-discovery -n istio-system --create-namespace --set istiod.revision=foo --set global.platform=(whatever) --set global.profile=(whatever)


  - title: Upgrading existing `Helm` or `istioctl` Istio installs with the `dataplane` wrapper chart
    content: |
      Using the `dataplane` wrapper chart to upgrade or migrate an existing Istio install that was originally installed with individual Helm charts or `istioctl` is not supported - you must upgrade with the same installation mechanism you used for the original install.
