apiVersion: v2
name: controlplane
description: Helm umbrella chart for Istio controlplane components
type: application
version: 1.0.0
appVersion: 1.0.0
kubeVersion: ">= 1.23.0-0"
keywords:
  - istiod
  - istio
  - controlplane
  - mesh
sources:
  - https://github.com/istio/istio
icon: https://istio.io/latest/favicons/android-192x192.png

# These will be stamped out to real versions during release publish
dependencies:
  - name: base
    version: 1.0.0
    repository: "file://../../charts/base"
  - name: istiod
    version: 1.0.0
    repository: "file://../../charts/istio-control/istio-discovery"
